service: default
runtime: python311

handlers:

- url: /
  static_files: my-docs/index2.html
  upload: my-docs/index2.html

- url: /
  static_dir: my-docs

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
