service: default
runtime: python311

handlers:

- url: /
  static_files: public/index2.html
  upload: public/index2.html

- url: /
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
